config/urls.py
from django.contrib import admin
from django.urls import path,include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include("pages.urls", namespace="pages")),
    path('listings/', include("listings.urls", namespace="listings")),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('admin/', admin.site.urls),
] + debug_toolbar_urls() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Medical Center Admin"
admin.site.site_title = "Medical Center Admin Portal"
admin.site.index_title = "Welcome to Medical Center Admin Portal"

contacts/urls.py
from django.urls import path
from . import views

app_name = 'contacts'

urlpatterns = [
    path('contact', views.contact, name='contact'),
    path('contact/delete/<int:contact_id>', views.delete_contact, name='delete_contact'),
    path('contact/edit/<int:contact_id>', views.edit_contact, name='edit_contact'),
]

listings/urls.py
from django.urls import path
from . import views

app_name = 'listings'

urlpatterns = [
    path('', views.listings, name='listings'),
    path('<int:listing_id>/', views.listing, name='listing'),
    path('search', views.search, name='search'),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about')
]

listings/models.py
from django.db import models
from datetime import datetime
from doctors.models import Doctor
from .choices import district_choices, room_choices, rooms_choices
from taggit.managers import TaggableManager
# Create your models here.

class Subject(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class Listing(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    district = models.CharField(max_length=50, choices=district_choices.items())
    description = models.TextField(blank=True)
    services = TaggableManager(verbose_name="Services")
    service = models.IntegerField()
    room_type = models.CharField(max_length=200, choices=room_choices.items(), default='')
    screen = models.IntegerField()
    professionals = models.ManyToManyField(Subject, blank=True)
    professional = models.IntegerField()
    rooms = models.CharField(max_length=2, choices=rooms_choices.items())
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/')
    photo_1 = models.ImageField(upload_to='photo/%Y/%m/%d/', blank=True)
    photo_2 = models.ImageField(upload_to='photo/%Y/%m/%d/', blank=True)
    photo_3 = models.ImageField(upload_to='photo/%Y/%m/%d/', blank=True)
    photo_4 = models.ImageField(upload_to='photo/%Y/%m/%d/', blank=True)
    photo_5 = models.ImageField(upload_to='photo/%Y/%m/%d/', blank=True)
    photo_6 = models.ImageField(upload_to='photo/%Y/%m/%d/', blank=True)
    is_published = models.BooleanField(default=True)
    list_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-list_date',)
        indexes = [models.Index(fields=['list_date'])]

    def __str__(self):
        return self.title
    
    def tag_list(self):
        return u", ".join(tag.name for tag in self.services.all())

listings/views.py
from django.shortcuts import render, get_object_or_404
from .models import Listing
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .choices import district_choices, room_choices, rooms_choices
from django.db.models import Q

# Create your views here.
def listings(request):
    # listings = Listing.objects.all()
    listings = Listing.objects.order_by('list_date').filter(is_published=True)
    paginator = Paginator(listings, 3)
    page = request.GET.get('page')
    paged_listings = paginator.get_page(page)
    context = {"listings": paged_listings}
    return render(request, 'listings/listings.html', context)


def listing(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    #listing = Listing.objects.get(id=listing_id)
    context = {"listing": listing}
    return render(request, 'listings/listing.html', context)

def search(request):
    queryset_list = Listing.objects.order_by('-list_date')
    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
            queryset_list = queryset_list.filter(Q(description__icontains=keywords) | Q(title__icontains=keywords) | Q(doctor__name__icontains=keywords))
    if 'district' in request.GET:
        district = request.GET['district']
        if district:
            queryset_list = queryset_list.filter(district__iexact=district)
    if 'rooms' in request.GET:
        rooms = request.GET['rooms']
        if rooms:
            queryset_list = queryset_list.filter(rooms__lte=rooms)
    if 'room_type' in request.GET:
        room_type = request.GET['room_type']
        if room_type:
            queryset_list = queryset_list.filter(room_type__iexact=room_type)
    paginator = Paginator(queryset_list, 3)
    page = request.GET.get('page')
    paged_listings = paginator.get_page(page)
    context = {"listings":paged_listings,
            "district_choices": district_choices,
            "room_choices":room_choices,
            "rooms_choices":rooms_choices,
            "values":request.GET
            }
    return render(request, 'listings/search.html', context)

templates/listings/listing.html
{% extends 'base.html' %} 
{% comment %} (DONE) {% endcomment %}
{% load humanize %}
<!--block title-->
{% block title %}{{listing.title}}{% endblock title %}
{% block content%} {% load static %}
    <section id="showcase-inner" class="py-5 text-white">
    <div class="container">
        <div class="row text-center">
        <div class="col-md-12">
            {% comment %} (DONE) {% endcomment %}
            <h1 class="display-4">{{listing.title | title}}</h1>
            {% comment %} (DONE) {% endcomment %}
            <p class="lead"><i class="fas fa-map-marker"></i>
                {{listing.district}}</p>
        </div>
        </div>
    </div>
    </section>

    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
    <div class="container">
        <nav>
        <ol class="breadcrumb">
        <li class="breadcrumb-item">
        {% comment %} (DONE) {% endcomment %}
        <a href={% url 'pages:index' %}>Home</a>
        </li>
        <li class="breadcrumb-item">
        {% comment %} (DONE) {% endcomment %}
        <a href={% url 'listings:listings' %}>Listings</a>
        </li>
        <li class="breadcrumb-item active">{{listing.title}}</li>
        </ol>
        </nav>
    </div>
    </section>

    <!-- Listing -->
    <section id="listing" class="py-4">
        {% include 'partials/_alert.html' %}
    <div class="container">
        {% comment %} (DONE) {% endcomment %}
        <a href={% url "listings:listings" %} class="btn btn-light mb-4">Back To Listings</a>
        <div class="row">
        <div class="col-md-9">j
            <!-- Home Main Image -->
            {% comment %} (DONE) {% endcomment %}
            <img
            src={{listing.photo_main.url}}
            alt=""
            class="img-main img-fluid mb-3"
            />
            <!-- Thumbnails -->
            <div class="row mb-5 thumbs">
            {% comment %} (DONE) {% endcomment %}
            {% if listing.photo_1 %}
            <div class="col-md-2">
                <a
                href={{listing.photo_1.url}}
                data-lightbox="home-images"
                >
                {% comment %} (DONE) {% endcomment %}
                <img
                    src={{listing.photo_1.url}}
                    alt=""
                    class="img-fluid"
                />
                </a>
            </div>
            {% endif %}
            {% comment %} (DONE) {% endcomment %}
            {% if listing.photo_2 %}
            <div class="col-md-2">
                
                <a
                href={{listing.photo_2.url}}
                data-lightbox="home-images"
                >
                {% comment %} (DONE) {% endcomment %}
                <img
                    src={{listing.photo_2.url}}
                    alt=""
                    class="img-fluid"
                />
                </a>
            </div>
            {% endif %}
            {% comment %} (DONE) {% endcomment %}
            {% if listing.photo_3 %}
            <div class="col-md-2">
                
                <a
                href={{listing.photo_3.url}}
                data-lightbox="home-images"
                >
                {% comment %} (DONE) {% endcomment %}
                <img
                    src={{listing.photo_3.url}}
                    alt=""
                    class="img-fluid"
                />
                </a>
            </div>
            {% endif %}
            {% comment %} (DONE) {% endcomment %}
            {% if listing.photo_4 %}
            <div class="col-md-2">
                
                <a
                href={{listing.photo_4.url}}
                data-lightbox="home-images"
                >
                {% comment %} (DONE) {% endcomment %}
                <img
                    src={{listing.photo_4.url}}
                    alt=""
                    class="img-fluid"
                />
                </a>
            </div>
            {% endif %}
            {% comment %} (DONE) {% endcomment %}
            {% if listing.photo_5 %}
            <div class="col-md-2">
                
                <a
                href={{listing.photo_5.url}}
                data-lightbox="home-images"
                >
                {% comment %} (DONE) {% endcomment %}
                <img
                    src={{listing.photo_5.url}}
                    alt=""
                    class="img-fluid"
                />
                </a>
            </div>
            {% endif %}
            {% comment %} (DONE) {% endcomment %}
            {% if listing.photo_6 %}
            <div class="col-md-2">
                
                <a
                href={{listing.photo_6.url}}
                data-lightbox="home-images"
                >
                {% comment %} (DONE) {% endcomment %}
                <img
                    src={{listing.photo_6.url}}
                    alt=""
                    class="img-fluid"
                />
                </a>
            </div>
            {% endif %}
            </div>
            <!-- Fields -->
            <div class="row mb-5 fields">
            <div class="col-md-6">
                <ul class="list-group list-group-flush">
                <li class="list-group-item text-secondary">
                    <i class="fas fa-money-bill-alt"></i> Inpatient Fee
                    Estimate:
                    <span class="float-right">$20,000/Day</span>
                </li>
                <li class="list-group-item text-secondary">
                    <i class="fas fa-bed"></i> Bedrooms:
                    <span class="float-right">30</span>
                </li>
                <li class="list-group-item text-secondary">
                    <i class="fas fa-bath"></i> Bathrooms:
                    <span class="float-right">Private</span>
                </li>
                <li class="list-group-item text-secondary">
                    <i class="fas fa-dumbbell"></i> Treatment:
                    <span class="float-right"> Have </span>
                </li>
                </ul>
            </div>
            <div class="col-md-6">
                <ul class="list-group list-group-flush">
                <li class="list-group-item text-secondary">
                    <i class="fas fa-th-large"></i> Restrooms:
                    <span class="float-right">Have</span>
                </li>
                <li class="list-group-item text-secondary">
                    <i class="fas fa-square"></i> Specialized Care:
                    <span class="float-right">No</span>
                </li>
                <li class="list-group-item text-secondary">
                    <i class="fas fa-calendar"></i> Preventative Services:
                    <span class="float-right">Have</span>
                </li>
                <li class="list-group-item text-secondary">
                    <i class="fas fa-bed"></i> Minor Surgical Procedures:
                    <span class="float-right">No</span>
                </li>
                </ul>
            </div>
            </div>

            <!-- Description -->
            <div class="row mb-5">
            <div class="col-md-12">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Mollitia recusandae esse reiciendis officia omnis non rerum
                dicta cupiditate nostrum molestias deserunt aut minus inventore
                animi atque, consequuntur ad fugit. Possimus culpa blanditiis
                repellendus ipsa similique ullam, natus error dolor harum.
            </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card mb-3">
            {% comment %}  {% endcomment %}
            <img
                class="card-img-top"
                src={{listing.doctor.photo.url}}
                alt="Seller of the month"
            />
            <div class="card-body">
                <h5 class="card-title">Medical Practitioner</h5>
                <h6 class="text-secondary">{{listing.doctor.name}}</h6>
            </div>
            </div>
            <button
            class="btn-primary btn-block btn-lg"
            data-toggle="modal"
            data-target="#inquiryModal"
            >
            Make An Inquiry
            </button>
        </div>
        </div>
    </div>
    </section>

    <!-- Inquiry Modal -->
    <div class="modal fade" id="inquiryModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="inquiryModalLabel">Make An Inquiry</h5>
            <button type="button" class="close" data-dismiss="modal">
            <span>&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form action="{% url 'contacts:contact' %}" method="POST" >
                {% csrf_token %}
                <input type="hidden" name="listing_id" value="{{listing.id}}" />
                {% if user.is_authenticated %}
                <input type="hidden" name="user_id" value="{{user.id}}" />
                {% else %}
                <input type="hidden" name="user_id" value="0" />
                {% endif %}
            <div class="form-group">
                <label for="clinic" class="col-form-label"
                >Clinic:</label
                >
                <input
                type="text"
                name="listing"
                class="form-control"
                value="{{listing.title}}"
                readonly
                />
            </div>
            <div class="form-group">
                <label for="name" class="col-form-label">Name:</label>
                <input type="text" name="name" class="form-control" 
                {% if user.is_authenticated %} 
                value="{{user.first_name}} {{user.last_name}}" readonly
                {% endif %} />
            </div>
            <div class="form-group">
                <label for="email" class="col-form-label">Email:</label>
                <input
                type="email"
                name="email"
                class="form-control"
                {% if user.is_authenticated %} 
                value="{{user.email}}" readonly
                {% endif %}
                />
            </div>
            <div class="form-group">
                <label for="phone" class="col-form-label">Phone:</label>
                <input type="text" name="phone" class="form-control" />
            </div>
            <div class="form-group">
                <label for="message" class="col-form-label">Message:</label>
                <textarea name="message" class="form-control"></textarea>
            </div>
            <hr />
            <input
                type="submit"
                value="Send"
                class="btn btn-block btn-secondary"
            />
            </form>
        </div>
        </div>
    </div>
    </div>
{% endblock %}

templates/listings/listings.html
{% extends 'base.html' %} 
<!-- load humanize-->
{% load humanize %}
<!--block title-->
{% block title %} | Clinic List {% endblock title %}
{% block content%} {% load static %}
<section id="showcase-inner" class="py-5 text-white">
      <div class="container">
        <div class="row text-center">
          <div class="col-md-12">
            <h1 class="display-4">Browse Our Clinic</h1>
            <p class="lead">
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt,
              pariatur!
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
      <div class="container">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              {% comment %} (DONE)index {% endcomment %}
              <a href={% url "pages:index" %} > <i class="fas fa-home"></i> Home</a>
            </li>
            <li class="breadcrumb-item active">Browse Listings</li>
          </ol>
        </nav>
      </div>
    </section>

    <!-- Listings -->
    <section id="listings" class="py-4">
      <div class="container">
        <div class="row">
          <!-- Listing 1 -->
          {% if listings %}
          {% for listing in listings %}
          <div class="col-md-6 col-lg-4 mb-4">
            <div class="card listing-preview">
              {% comment %} (DONE)image {% endcomment %}
              <img
                class="card-img-top"
                src={{listing.photo_main.url}}
                alt=""
              />
              <div class="card-img-overlay">
              </div>
              <div class="card-body">
                <div class="listing-heading text-center">
                  <h4 class="text-primary">{{listing.title | title}}</h4>
                  <p>
                    <i class="fas fa-map-marker text-secondary"></i> {{listing.district | title}}
                  </p>
                </div>
                <hr />
                <div class="row py-2 text-secondary">
                  <div class="col-6">
                    <i class="fas fa-th-large"></i> Services {{listing.service}}
                  </div>
                  <div class="col-6">
                    <i class="fas fa-dumbbell"></i> Screens {{listing.screen}} 
                  </div>
                </div>
                <div class="row py-2 text-secondary">
                  <div class="col-6">
                    <i class="fas fa-bed"></i> Rooms {{listing.rooms}}
                  </div>
                  <div class="col-6">
                    <i class="fas fa-bath"></i> Professionals {{listing.professional}}
                  </div>
                </div>
                <hr />
                <div class="row py-2 text-secondary">
                  <div class="col-12"><i class="fas fa-user"></i> {{listing.doctor.name}} </div>
                </div>
                <div class="row text-secondary pb-2">
                  <div class="col-12">
                    <i class="fas fa-clock"></i> Reservation required
                  </div>
                </div>
                <hr />
                {% comment %} (DONE)listing {% endcomment %}
                <a href={% url "listings:listing" listing.id %} class="btn btn-primary btn-block"
                  >More Info</a
                >
              </div>
            </div>
          </div>
          {% endfor %}
          {% else %}
          <div class="col-md-12">
            <p>No Clinic available</p>
          </div>
          {% endif %}
          
        </div>

        <div class="row">
          <div class="col-md-12">
            {% if listings.has_other_pages %}
            <ul class="pagination">
              {% if listings.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page=
                {{listings.previous_page_number}}">&laquo;</a>
              </li>
              {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#">&laquo;</a>
              </li>
              {% endif %}
              {% for i in listings.paginator.page_range %}
              {% if listings.number == i %}
              <li class="page-item active">
                <a class="page-link">{{i}}</a>
              </li>
              {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{i}}">{{i}}</a>
              </li>
              {% endif %}
              {% endfor %}
              {% if listings.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page=
                {{listings.next_page_number}}">&raquo;</a>
              </li>
              {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#">&raquo;</a>
              </li>
              {% endif %}
            </ul>
            {% endif %}
          </div>
        </div>
      </div>
    </section>

{% endblock %}

templates/listings/search.html
{% extends 'base.html' %} {% block content%} {% load static %}
#<h1>search.html</h1>
<section id="showcase-inner" class="showcase-search text-white py-5">
    <div class="container">
        <div class="row text-center">
        <div class="col-md-12">
            {% comment %} search {% endcomment %}
            <form action="{% url 'listings:search' %}">
            <!-- Form Row 1 -->
            <div class="form-row">
                <div class="col-md-12 mb-3">
                <label class="sr-only">Keywords</label>
                <input
                    type="text"
                    name="keywords"
                    class="form-control"
                    placeholder="Keyword (Clinic, Doctor, City name, Town name, etc)"
                    value="{{values.keywords}}"
                />
                </div>
            </div>
            <!-- Form Row 2 -->
            <div class="form-row">
                <div class="col-md-4 mb-3">
                <label class="sr-only">District</label>
                <select name="district" class="form-control">
                    <option {% if not values.district %} selected="true" {% endif %} value=''>
                    District (All)
                    </option>
                    {% for key,value in district_choices.items %}
                    <option value="{{key}}" {% if key == values.district %} selected="true" {% endif %}>{{value}}</option>
                    {% endfor %}
                </select>
                </div>
                <div class="col-md-4 mb-3">
                <label class="sr-only">Rooms</label>
                <select name="rooms" class="form-control">
                    <option {% if not values.rooms %} selected="true" {% endif %} value=''>
                    Room (All)
                    </option>
                    {% for key,value in rooms_choices.items %}
                    <option value="{{key}}" {% if key == values.rooms %} selected="true" {% endif %}>{{value}}</option>
                    {% endfor %}
                </select>
                </div>
                <div class="col-md-4 mb-3">
                <select name="room_type" class="form-control" id="type">
                    <option {% if not values.room_type %} selected="true" {% endif %} value=''>
                    Room Type (All)
                    </option>
                    {% for key,value in room_choices.items %}
                    <option value="{{key}}" {% if key == values.room_type %} selected="true" {% endif %} >{{value}}</option>
                    {% endfor %}
                </select>
                </div>
            </div>
            <button class="btn btn-secondary btn-block mt-4" type="submit">
                Submit form
            </button>
            </form>
        </div>
        </div>
    </div>
    </section>

    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
    <div class="container">
        <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                {% comment %} index {% endcomment %}
            <a href={% url 'pages:index' %}> <i class="fas fa-home"></i> Home</a>
            </li>
            <li class="breadcrumb-item">
                {% comment %} listings {% endcomment %}
            <a href={% url 'listings:listings' %}>Browse Listings</a>
            </li>
            <li class="breadcrumb-item active">Search Results</li>
        </ol>
        </nav>
    </div>
    </section>

    <!-- Listings -->
    <section id="listings" class="py-4">
    <div class="container">
        <div class="row">
        <!-- Listing 1 -->
        {% if listings %}
        {% for listing in listings %}
        <div class="col-md-6 col-lg-4 mb-4">
            <div class="card listing-preview">
            {% comment %} (DONE)image {% endcomment %}
            <img
                class="card-img-top"
                src={{listing.photo_main.url}}
                alt=""
            />
            <div class="card-img-overlay">
            </div>
            <div class="card-body">
                <div class="listing-heading text-center">
                <h4 class="text-primary">{{listing.title | title}}</h4>
                <p>
                    <i class="fas fa-map-marker text-secondary"></i> {{listing.district | title}}
                </p>
                </div>
                <hr />
                <div class="row py-2 text-secondary">
                <div class="col-6">
                    <i class="fas fa-th-large"></i> Services {{listing.service}}
                </div>
                <div class="col-6">
                    <i class="fas fa-dumbbell"></i> Screens {{listing.screen}} 
                </div>
                </div>
                <div class="row py-2 text-secondary">
                <div class="col-6">
                    <i class="fas fa-bed"></i> Rooms {{listing.rooms}}
                </div>
                <div class="col-6">
                    <i class="fas fa-bath"></i> Professionals {{listing.professional}}
                </div>
                </div>
                <hr />
                <div class="row py-2 text-secondary">
                <div class="col-12"><i class="fas fa-user"></i> {{listing.doctor.name}} </div>
                </div>
                <div class="row text-secondary pb-2">
                <div class="col-12">
                    <i class="fas fa-clock"></i> Reservation required
                </div>
                </div>
                
                <hr />
                {% comment %} (DONE)listing {% endcomment %}
                <a href={% url "listings:listing" listing.id %} class="btn btn-primary btn-block"
                >More Info</a
                >
            </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="col-md-12">
            <p>No Clinic available</p>
        </div>
        {% endif %}
        
        </div>
        {% comment %} paganation {% endcomment %}
        <div class="row">
        <div class="col-md-12">
            {% if listings.has_other_pages %}
            <ul class="pagination">
            {% if listings.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=
                {{listings.previous_page_number}}&keywords={{values.keywords}}&district={{values.district}}&rooms={{values.rooms}}&room_type={{values.room_type}}">&laquo;</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">&laquo;</a>
            </li>
            {% endif %}
            {% for i in listings.paginator.page_range %}
            {% if listings.number == i %}
            <li class="page-item active">
                <a class="page-link">{{i}}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{i}}&keywords={{values.keywords}}&district={{values.district}}&rooms={{values.rooms}}&room_type={{values.room_type}}">{{i}}</a>
            </li>
            {% endif %}
            {% endfor %}
            {% if listings.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page=
                {{listings.next_page_number}}&keywords={{values.keywords}}&district={{values.district}}&rooms={{values.rooms}}&room_type={{values.room_type}}">&raquo;</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">&raquo;</a>
            </li>
            {% endif %}
            </ul>
            {% endif %}
        </div>
        </div>
    </div>
    </section>
{% endblock %}